#!/bin/bash
#
# Runs a service container.
#

set -e

cd "$(dirname "$0")/../.."

docker container run \
    --rm \
    --interactive \
    --tty \
    --publish 4000:4000 \
    --name adwell \
    --env-file .env \
    MY_PROJECT-production bin/server
