#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Setting up assets…"
mix do --app MY_PROJECT_web assets.setup, assets.build

echo "==> Setting up DB…"
# reset database to a fresh state.
eval "$(read_env)" mix ecto.reset

echo "==> The project is setup! 🚀 Is there demo data to load?"
