#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Setting up DB…"
# reset database to a fresh state.
# mix ecto.reset

if [ -f ".env" ]; then
    echo "==> Creating backup for .env…"
    cp .env .env.backup
fi

cp .env.template .env

echo "==> App is now ready to go! 🚀"
echo "==> Please update the .env file with the correct values."
